---

- name: Create /var/www
  ansible.builtin.file:
    path: /var/www
    state: directory
    owner: caddy
    group: caddy
    mode: '0600'
  notify: reload caddy

- name: Gather IPFS hashes from VOD files
  ansible.builtin.command:
    cmd: "/root/futureporn/utils/export.js --mode cidlist"
  register: vodlist

- debug: var=vodlist

- name: create whitelisted_cids
  ansible.builtin.set_fact:
    whitelisted_cids: "{{ vodlist.stdout }}"

- name: Configure Caddy
  ansible.builtin.template:
    src: templates/Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: caddy
    group: caddy
    mode: '0600'
  notify: reload caddy

