---


- name: Download futureporn from git
  ansible.builtin.git:
    repo: 'https://github.com/insanity54/futureporn'
    dest: /root/futureporn
    force: yes
    clone: yes
    update: yes

- name: Install yarn
  community.general.npm:
    name: yarn
    global: yes

- name: install futureporn nodejs project
  community.general.yarn:
    path: /root/futureporn
    production: yes
    state: present