---


- name: provision the MQTT broker
  hosts: broker
  vars:
    REDIS_HOST: "{{ lookup('env', 'REDIS_HOST') }}"
    REDIS_PORT: "{{ lookup('env', 'REDIS_PORT') }}"
    REDIS_PASSWORD: "{{ lookup('env', 'REDIS_PASSWORD') }}"
    REDIS_USERNAME: "{{ lookup('env', 'REDIS_USERNAME') }}"
    AEDES_PASSWORD_HASH: "{{ lookup('env', 'AEDES_PASSWORD_HASH') }}"
    AEDES_PASSWORD_SALT: "{{ lookup('env', 'AEDES_PASSWORD_SALT') }}"
    ansible_user: root
    nodejs_version: "18.x"
  roles:
    - role: geerlingguy.nodejs
    - role: broker
      tags: [broker]