---

- hosts: localhost
  gather_facts: no
  vars:
    - vps_plan: vc2-2c-4gb
    - vps_hostname: futureporn-capture
    - vps_region: dfw
  roles:
    - role: spinup

- hosts: futureporn-capture
  gather_facts: no
  vars:
    - ansible_user: root
  roles:
    - role: spinup
    - role: base
    - role: geerlingguy.nodejs
    - role: capture
    - role: scout
