---

- name: reload caddy
  ansible.builtin.systemd:
    name: caddy
    state: reloaded
    daemon_reload: yes

- name: restart companion
  ansible.builtin.systemd:
    name: companion
    state: restarted
    daemon_reload: yes

    