---

- name: create futureporn user
  ansible.builtin.user:
    name: futureporn
    groups: futureporn
    create_home: true
    home: /home/futureporn

- name: create futureporn group
  ansible.builtin.group:
    name: futureporn

- name: upload/install ssh deploy key
  copy:
    remote_src: false
    path: /home/chris/.ssh/futureporn-builder
    dest: /home/futureporn/futureporn/.ssh/futureporn-builder
    mode: '0600'
  become: yes
  become_user: futureporn

- name: install yarn
  community.general.npm:
    name: yarn
    global: yes
    state: present
  become: yes
  become_user: futureporn

- name: Download futureporn
  git:
    repo: https://github.com/insanity54/futureporn
    dest: /home/futureporn/futureporn
    depth: 1
    update: yes
    force: yes
  notify:
    - restart builder
  become: yes
  become_user: futureporn
  
- name: Install futureporn
  community.general.yarn:
    path: /home/futureporn/futureporn/builder
  notify:
    - restart builder
  become: yes
  become_user: futureporn
  

- name: Install builder system service
  ansible.builtin.template:
    src: templates/builder.service.j2
    dest: /etc/systemd/system/builder.service
    owner: root
    group: root
    mode: '0755'
  notify: 
    - restart builder

- name: Enable builder system service
  systemd:
    name: builder
    state: started
    daemon_reload: yes
    enabled: yes
  notify:
    - restart builder

