---

- debug: var=instance_count

- name: Create a Vultr instance
  vultr.cloud.instance:
    label: "futureporn-{{ instance_type }}{{ item }}"
    hostname: "futureporn-{{ instance_type }}{{ item }}"
    # package requirements differ slightly for 
    # cluster vs capture roles so 
    # we only want to set packages that are commonly
    # used for all roles
    user_data: |
      #cloud-config
      packages:
        - python3
        - python3-pip
        - mg 
        - git
        - magic-wormhole
        - mosh
    plan: "{{ instance_plan }}"
    ddos_protection: false
    backups: false
    enable_ipv6: true
    ssh_keys:
      - LEO-COMPUTE
    tags:
      - "{{ instance_type }}"
    region: dfw
    os: Ubuntu 22.04 LTS x64
  loop: "{{ range(1, (instance_count|int+1), 1)|list }}"
  notify:
    - refresh inventory
