---


- name: debug
  debug:
    var: task

- include: ./provision.yml
  when: task == "provision"

- include: ./b2-linux.yml
  when: task == "provision"

- include: ./upload.yml
  when: task == "upload"

- include: ./ls.yml
  when: task == "ls"

