---

- name: Download screen configuration
  git:
    repo: 'https://github.com/insanity54/dotfiles'
    dest: /root/dotfiles

- name: Configure screen
  copy:
    src: /root/dotfiles/.screenrc
    dest: /root/.screenrc
    remote_src: yes


- name: install yarn
  community.general.npm:
    name: yarn
    global: yes
    state: present

- name: Install & update youtube-dl
  pip:
    name: youtube-dl
    state: latest


- name: Install futureporn
  git:
    repo: https://github.com/insanity54/futureporn
    dest: /root/futureporn
    force: yes

- name: Install & update voddo
  git:
    repo: 'https://github.com/insanity54/voddo'
    dest: /root/voddo

- name: Install voddo system service
  ansible.builtin.template:
    src: templates/voddo.service.j2
    dest: /etc/systemd/system/voddo.service
    owner: root
    group: root
    mode: '0755'
  notify: 
    - restart voddo

- name: Enable voddo system service
  systemd:
    name: voddo
    state: started
    daemon_reload: yes
    enabled: yes
  notify:
    - restart voddo

- name: Download ipfs-cluster-ctl
  ansible.builtin.unarchive:
    remote_src: yes
    src: https://dist.ipfs.tech/ipfs-cluster-ctl/v1.0.2/ipfs-cluster-ctl_v1.0.2_linux-amd64.tar.gz
    dest: /root/


  # futureporn.mjs needs this to upload files to the ipfs cluster
- name: Install ipfs-cluster-ctl
  ansible.builtin.copy:
    remote_src: yes
    src: /root/ipfs-cluster-ctl/ipfs-cluster-ctl
    dest: /usr/local/bin/ipfs-cluster-ctl
    mode: '0755'
