---


- name: Set WEB3_TOKEN secret in env
  ansible.builtin.lineinfile:
    dest: /root/.bashrc
    line: "export WEB3_TOKEN={{ lookup('env', 'WEB3_TOKEN') }}"
    state: present

- name: Install latest rclone
  apt:
    deb: https://downloads.rclone.org/rclone-current-linux-amd64.deb
    state: present
    # this is necessary because the apt version has a B2 upload bug

- name: create ufw exception for mosh
  community.general.ufw:
    rule: allow
    port: 60000:61000
    proto: udp

- name: Create rclone conf directory
  ansible.builtin.file:
    state: directory
    path: /root/.config/rclone
    mode: '0755'

- name: Configure rclone
  ansible.builtin.template:
    src: templates/rclone.conf.j2
    dest: /root/.config/rclone/rclone.conf
    owner: root
    group: root
    mode: '0600'

- name: Download screen configuration
  git:
    repo: 'https://github.com/insanity54/dotfiles'
    dest: /root/dotfiles

- name: Configure screen
  copy:
    src: /root/dotfiles/.screenrc
    dest: /root/.screenrc
    remote_src: yes

- name: Install & update youtube-dl
  pip:
    name: youtube-dl
    state: latest

- name: Install futureporn
  git:
    repo: https://github.com/insanity54/futureporn
    dest: /root/futureporn

- name: Install & update voddo
  git:
    repo: 'https://github.com/insanity54/voddo'
    dest: /root/voddo

- name: Install voddo system service
  ansible.builtin.template:
    src: templates/voddo.service.j2
    dest: /etc/systemd/system/voddo.service
    owner: root
    group: root
    mode: '0755'
  notify: 
    - restart voddo

- name: Enable voddo system service
  systemd:
    name: voddo
    state: started
    daemon_reload: yes
    enabled: yes
  notify:
    - restart voddo



