---

- name: Set B2_APPLICATION_KEY in env
  ansible.builtin.lineinfile:
    dest: /root/.bashrc
    line: "export B2_APPLICATION_KEY={{ lookup('env', 'B2_APPLICATION_KEY') }}"
    state: present

- name: Set B2_APPLICATION_KEY_ID in env
  ansible.builtin.lineinfile:
    dest: /root/.bashrc
    line: "export B2_APPLICATION_KEY_ID={{ lookup('env', 'B2_APPLICATION_KEY_ID') }}"
    state: present

- name: Set WEB3_TOKEN secret in env
  ansible.builtin.lineinfile:
    dest: /root/.bashrc
    line: "export WEB3_TOKEN={{ lookup('env', 'WEB3_TOKEN') }}"
    state: present

- name: Set TWITTER_API_KEY in env
  ansible.builtin.lineinfile:
    dest: /root/.bashrc
    line: "export TWITTER_API_KEY={{ lookup('env', 'TWITTER_API_KEY') }}"
    state: present

- name: Set TWITTER_API_KEY_SECRET in env
  ansible.builtin.lineinfile:
    dest: /root/.bashrc
    line: "export TWITTER_API_KEY_SECRET={{ lookup('env', 'TWITTER_API_KEY_SECRET') }}"
    state: present

- name: Install latest rclone
  apt:
    deb: https://downloads.rclone.org/rclone-current-linux-amd64.deb
    state: present
    # this is necessary because the apt version has a B2 upload bug



- name: Create rclone conf directory
  ansible.builtin.file:
    state: directory
    path: /root/.config/rclone
    mode: '0755'

- name: Configure rclone
  ansible.builtin.template:
    src: templates/rclone.conf.j2
    dest: /root/.config/rclone/rclone.conf
    owner: root
    group: root
    mode: '0600'

- name: Download screen configuration
  git:
    repo: 'https://github.com/insanity54/dotfiles'
    dest: /root/dotfiles

- name: Configure screen
  copy:
    src: /root/dotfiles/.screenrc
    dest: /root/.screenrc
    remote_src: yes

- name: Install & update youtube-dl
  pip:
    name: youtube-dl
    state: latest

- name: Install futureporn
  git:
    repo: https://github.com/insanity54/futureporn
    dest: /root/futureporn

- name: Install & update voddo
  git:
    repo: 'https://github.com/insanity54/voddo'
    dest: /root/voddo

- name: Install voddo system service
  ansible.builtin.template:
    src: templates/voddo.service.j2
    dest: /etc/systemd/system/voddo.service
    owner: root
    group: root
    mode: '0755'
  notify: 
    - restart voddo

- name: Enable voddo system service
  systemd:
    name: voddo
    state: started
    daemon_reload: yes
    enabled: yes
  notify:
    - restart voddo



