---



- name: Create the caddy group
  ansible.builtin.user:
    name: caddy

- name: Create the caddy user
  ansible.builtin.user:
    name: caddy
    groups: caddy
    create_home: no

- name: Create the uppy group
  ansible.builtin.user:
    name: uppy

- name: Create the uppy user
  ansible.builtin.user:
    name: uppy
    groups: uppy
    create_home: yes
    home: /home/uppy