
# greets https://grafana.com/docs/grafana-cloud/infrastructure-as-code/ansible/ansible-grafana-agent-linux/

- name: add group 'grafana-agent'
  ansible.builtin.group:
    name: grafana-agent

- name: Add user 'grafana-agent'
  user:
    name: grafana-agent
    groups: grafana-agent
    create_home: true
    home: /home/grafana-agent
    shell: /bin/false

- name: create cache dir
  file:
    state: directory
    path: /home/grafana-agent/.cache/
    owner: grafana-agent
    group: grafana-agent

- name: create positions dir
  file:
    state: directory
    path: /home/grafana-agent/positions/
    owner: grafana-agent
    group: grafana-agent

- name: ensure unzip is installed
  apt:
    name: unzip
    state: present

- name: Create directory for config
  file:
    path: "{{ agent_config_location }}"
    state: directory
    mode: '0755'


- name: Download Grafana Agent binary
  get_url:
    url: "https://github.com/grafana/agent/releases/download/{{ agent_version }}/agent-linux-{{ linux_architecture }}.zip"
    dest: "/tmp/agent-linux.zip"
    mode: '0644'


- name: Unarchive Grafana Agent binary
  unarchive:
    src: "/tmp/agent-linux.zip"
    dest: "{{ agent_binary_location }}"
    remote_src: true
    mode: '0755'




- name: Create config file for Grafana Agent
  template:
    src: grafana-agent.yml.j2
    dest: "{{ agent_config_location }}/grafana-agent.yml"
  notify: restart grafana-agent




- name: Create service file for Grafana Agent
  template:
    src: grafana-agent.service.j2
    dest: "/etc/systemd/system/grafana-agent.service"

- name: Start Grafana Agent service
  systemd:
    daemon_reload: true
    name: grafana-agent
    enabled: true
    state: restarted
