---


- name: reload caddy
  ansible.builtin.systemd:
    name: caddy
    state: reloaded
    daemon_reload: yes

- name: init ipfs
  ansible.builtin.command:
    args: ipfs init
    
- name: restart ipfs
  ansible.builtin.systemd:
    name: ipfs
    state: restarted
    daemon_reload: yes