---




- name: install yarn
  community.general.npm:
    name: yarn
    global: yes
    state: present

- name: Download futureporn
  git:
    repo: https://github.com/insanity54/futureporn
    dest: /home/futureporn/futureporn
    depth: 1
    update: yes
    force: yes
  notify:
    - restart commander
  become: yes
  become_user: futureporn

# not needed because of berry zero-install
# - name: Install futureporn commander
#   command:
#     yarn install
#   community.general.yarn:
#     path: /home/futureporn/futureporn/packages/commander
#     production: yes
#   notify:
#     - restart commander
#   become: yes
#   become_user: futureporn

- name: Install commander system service
  ansible.builtin.template:
    src: templates/commander.service.j2
    dest: /etc/systemd/system/commander.service
    owner: root
    group: root
    mode: '0755'
  notify: 
    - restart commander

- name: Enable commander system service
  systemd:
    name: commander
    state: started
    daemon_reload: yes
    enabled: yes
  notify:
    - restart commander


