---

- apt:
    name: 
      - postgresql
      - python3-psycopg2
    state: present



- name: Create postgres admin user
  community.postgresql.postgresql_user:
    name: futureporn
    password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"
  become: yes
  become_user: postgres
  notify:
    - reload postgresql

- name: Create a futureporn database
  community.postgresql.postgresql_db:
    name: futureporn
    state: present
  become: yes
  become_user: postgres
  notify:
    - reload postgresql


- name: Grant futureporn user remote access to db
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/13/main/pg_hba.conf
    contype: host
    users: futureporn
    address: all
    databases: futureporn
    method: md5
  notify:
    - reload postgresql

# - name: Grant ALL privs on postgres to futureporn user
#   community.postgresql.postgresql_privs:
#     db: postgres
#     privs: ALL
#     type: database
#     role: futureporn
#   become: yes
#   become_user: postgres
#   notify:
#     - reload postgresql

# - name: Grant ALL privs on futureporn to futureporn user
#   community.postgresql.postgresql_privs:
#     db: futureporn
#     privs: ALL
#     type: database
#     role: futureporn
#   become: yes
#   become_user: postgres
#   notify:
#     - reload postgresql

- name: ensure postgres is running
  systemd:
    name: postgresql
    state: started