---

- name: spin up instances
  hosts: localhost
  vars:
    - instance_plan: vc2-1c-2gb
    - instance_count: 3
    - instance_type: capture
  roles:
    - role: spinup


- name: install futureporn capture suite
  hosts: ~futureporn-capture\d
  gather_facts: no
  vars:
    - ansible_user: root
    - nodejs_version: "16.x"
    - ipfs_version: v0.12.2
    - ipfs_private_key: "{{ lookup('env', 'IPFS_PRIVATE_KEY') }}"
    - ipfs_peer_id: "{{ lookup('env', 'IPFS_PEER_ID') }}"
    - nodejs_version: "16.x"
    - storage_gb: 40 # minimum 40GB
    - ipfs_storage_max: "40GB" 
  roles:
    - role: base
    - role: geerlingguy.nodejs
    
    - role: capture
      tags: [capture]

    - role: jeffbr13.ipfs 

    # important that manager comes after jeffbr13.ipfs
    # as we monkey patch the ipfs.service file
    - role: manager 


- name: install futureporn-scout just on one VPS
  hosts: futureporn-capture1
  gather_facts: no # just for speed
  vars:
    - ansible_user: root
  roles:
    - role: scout
      tags: [scout]