---

- hosts: localhost
  tasks:
  - name: Ensure futureporn-capture is spun down
    ngine_io.vultr.vultr_server:
      name: futureporn-capture
      state: absent

  - name: Ensure futureporn-manager is spun down
    ngine_io.vultr.vultr_server:
      name: futureporn-manager
      state: absent