---

- name: cluster monolith for a dedicated server
  hosts: monoliths
  gather_facts: no # `no` is a requirement for insanity54/base role. the base role gather facts once able.
  vars:
    - ansible_user: root
    - storage_gb: 3000
    - ipfs_gc_period: 3h
    - ipfs_cluster_service_version: v1.0.5
    - ipfs_cluster_service_checksum: sha256:842be4c780848e8d744ff0cdb410b3f88024af63f02d3d41cc040905fbcc6f8f
    - certbot_admin_email: "{{ lookup('env', 'LUA_DNS_EMAIL') }}"
    - certbot_create_command: "certbot certonly --noninteractive --dns-luadns --dns-luadns-credentials /etc/letsencrypt/luadns.ini --agree-tos --email {{ cert_item.email | default(certbot_admin_email) }} -d {{ cert_item.domains | join(',') }}"
    - certbot_create_standalone_stop_services: [nginx]
    - certbot_create_if_missing: yes
    - certbot_certs:
      - domains:
        - "*.futureporn.net"
  pre_tasks:
    - name: de-boogie
      ansible.builtin.debug:
        msg: "REDIS_HOST:{{ lookup('env', 'REDIS_HOST') }}"
      tags: [capture]
    - name: gather facts only if specific tag is used
      gather_facts:
      tags: 
        - never
        - gateway
        - cluster
        - scout
        - capture
        - grafana
  roles:
    - role: base
      tags: [base]
    - role: ipfs # also installs/configures IPFS, caddy
      tags: [ipfs]
    - role: cluster
      tags: [cluster]
    - role: geerlingguy.nodejs
      tags: 
        - capture
        - scout
    - role: capture
      tags: [capture]
    - role: scout
      tags: [scout]
    - role: qa
      tags: [qa]
    - role: grafana
      tags: [grafana]
