---

- name: cluster and gateway and basically a monolith for a dedicated server
  hosts: monoliths
  gather_facts: no # `no` is a requirement for insanity54/base role. the base role gather facts once able.
  vars:
    - ansible_user: root
    - storage_gb: 3000
    - ipfs_gc_period: 3h
    - ipfs_cluster_service_version: v1.0.4
  pre_tasks:
    - name: de-boogie
      ansible.builtin.debug:
        msg: "REDIS_HOST:{{ lookup('env', 'REDIS_HOST') }}"
      tags: [capture]
    - name: gather facts only if specific tag is used
      gather_facts:
      tags: 
        - never
        - gateway
        - cluster
        - scout
        - capture
  roles:
    - role: base
    - role: nvjacobo.caddy
      tags:
        - gateway
    - role: gateway # also installs/configures IPFS
      tags: [gateway]
    - role: cluster
      tags: [cluster]
    - role: geerlingguy.nodejs
      tags: 
        - capture
        - scout
    - role: capture
      tags: [capture]
    - role: scout
      tags: [scout]
    - role: qa
      tags: [qa]
