---





- name: Ensure futureporn is updated
  git:
    repo: https://github.com/insanity54/futureporn
    dest: /home/futureporn/futureporn
    depth: 1
    update: yes
    force: yes
  become: true
  become_user: futureporn

- name: ensure yarn is installed
  community.general.npm:
    name: yarn
    global: yes
  become: true
  become_user: futureporn

# no longer needed because https://yarnpkg.com/features/zero-installs
# - name: install scout
#   community.general.yarn:
#     path: /home/futureporn/futureporn/packages/scout
#   become: true
#   become_user: futureporn

- name: create datadir
  file:
    path: /home/futureporn/.local/share/futureporn/scout
    state: directory
    owner: futureporn
    group: futureporn

- name: Install scout system service
  ansible.builtin.template:
    src: templates/scout.service.j2
    dest: /etc/systemd/system/scout.service
    owner: root
    group: root
    mode: '0755'
  notify: 
    - restart scout

- name: Enable scout system service
  systemd:
    name: scout
    state: started
    daemon_reload: yes
    enabled: yes
  notify:
    - restart scout

