---


- name: Set Twitter api key in env
  ansible.builtin.lineinfile:
    dest: /root/.bashrc
    line: "export TWITTER_API_KEY={{ lookup('env', 'TWITTER_API_KEY') }}"
    state: present

- name: Set Twitter secret in env
  ansible.builtin.lineinfile:
    dest: /root/.bashrc
    line: "export TWITTER_API_KEY_SECRET={{ lookup('env', 'TWITTER_API_KEY_SECRET') }}"
    state: present

- name: Ensure futureporn is updated
  git:
    repo: https://github.com/insanity54/futureporn
    dest: /root/futureporn
    depth: 1
    update: yes
    force: yes

- name: ensure yarn is installed
  community.general.npm:
    name: yarn
    global: yes

- name: install futureporn
  community.general.yarn:
    path: /root/futureporn


- name: Install scout system service
  ansible.builtin.template:
    src: templates/scout.service.j2
    dest: /etc/systemd/system/scout.service
    owner: root
    group: root
    mode: '0755'
  notify: 
    - restart scout

- name: Enable scout system service
  systemd:
    name: scout
    state: started
    daemon_reload: yes
    enabled: yes
  notify:
    - restart scout

