---


- name: restart commander
  ansible.builtin.systemd:
    name: commander
    state: restarted


- name: reload postgresql
  ansible.builtin.systemd:
    name: postgresql
    state: reloaded


- name: reload caddy
  ansible.builtin.systemd:
    name: caddy
    state: reloaded
    daemon_reload: yes
