---


# nvjacobo.caddy takes care of the following 3 tasks. make sure that runs first.

- name: Create the caddy group
  ansible.builtin.group:
    name: caddy


- name: Create the caddy user
  ansible.builtin.user:
    name: caddy
    groups: caddy
    create_home: yes
    home: /home/caddy
  ignore_errors: true


- name: Install caddy system service
  ansible.builtin.template:
    src: templates/caddy.service.j2
    dest: /etc/systemd/system/caddy.service
    owner: root
    group: root
    mode: '0755'
  notify: 
    - reload caddy


- name: Create /usr/local/bin/etc/caddy
  ansible.builtin.file:
    path: /usr/local/bin/etc/caddy
    state: directory
    owner: caddy
    group: caddy
    mode: '0600'
  notify: reload caddy


- name: copy custom-built caddy to server
  ansible.builtin.copy:
    remote_src: false
    src: /home/chris/tmpdev/caddy-security/bin/authp
    dest: /usr/local/bin/caddy
    mode: '0755'


- name: Configure Caddy
  ansible.builtin.template:
    src: templates/Caddyfile.j2
    dest: /usr/local/etc/caddy/Caddyfile
    owner: root
    group: root
    mode: '0755'
  notify: reload caddy


- name: stop nginx
  ansible.builtin.systemd:
    name: nginx
    state: stopped
  notify:
    - disable nginx
  ignore_errors: true


- name: start & enable caddy
  ansible.builtin.systemd:
    name: caddy
    state: started
    enabled: true
    daemon_reload: true
  ignore_errors: true


# - name: mkdir for caddy
#   ansible.builtin.file:
#     state: directory
#     dest: /usr/local/etc/caddy
#     owner: root
#     group: root
#     mode: '0755'

# - name: mkdir for www
#   file:
#     state: directory
#     dest: /var/www/sbtp.xyz
#     owner: caddy
#     group: caddy
#     mode: '0755'

# - name: copy index.html to server
#   ansible.builtin.copy:
#     remote_src: false
#     src: files/index.html
#     dest: /var/www/sbtp.xyz/index.html
#     owner: caddy
#     group: caddy
#     mode: '0744'



# - name: Install caddy init file
#   ansible.builtin.template:
#     src: templates/caddy.service.j2
#     dest: 